In [2]:
import pandas as pd
import os
from IPython.display import display

In [22]:
downloads_path = os.path.expanduser('~/Downloads')
csv_files = ['events_header.csv','users.csv','campaigns.csv']

In [23]:
all_dataframes = {}
for file in csv_files:
    file_path = os.path.join(downloads_path, file)
    df = pd.read_csv(file_path)
    display(df.head(3))
    print("\n")

,EventID,AdvertiserName,CampaignName,CampaignStartDate,CampaignEndDate,CampaignTargetingCriteria,CampaignTargetingInterest,CampaignTargetingCountry,AdSlotSize,UserID,Device,Location,Timestamp,BidAmount,AdCost,WasClicked,ClickTimestamp,AdRevenue,Budget,RemainingBudget
0,e067dae7-9aaa-4b9c-9195-7af63ce89216,Advertiser_30,Campaign_278,2024-10-10,2024-11-12,Age 29-46,Gaming,Germany,300x250,289903,Mobile,USA,2024-10-31T06:56:39,4.60,3.70,False,NaN,0.0,279306.60,279306.60
1,ea95edfa-1ba0-444d-a40d-a3f064dd5791,Advertiser_25,Campaign_235,2024-10-24,2024-11-28,Age 22-33,Gaming,Australia,728x90,145276,Desktop,UK,2024-11-13T09:19:34,3.50,2.85,False,NaN,0.0,88914.60,88914.60
2,5f12c537-ac88-4fcc-8d23-b3fa2b538a3b,Advertiser_95,Campaign_947,2024-10-31,2024-11-11,Age 27-42,Health,USA,300x250,83608,Desktop,USA,2024-11-08T14:36:14,3.75,3.16,False,NaN,0.0,207892.45,207892.45

,UserID,Age,Gender,Location,Interests,SignupDate
0,1,58,Male,USA,"Gaming,Sports,Health",2020-07-28
1,2,61,Male,Australia,"Technology,Education,Health,Sports",2021-04-21
2,3,50,Male,Australia,"Health,Sports",2022-07-08

,CampaignID,AdvertiserName,CampaignName,CampaignStartDate,CampaignEndDate,TargetingCriteria,AdSlotSize,Budget,RemainingBudget
0,1,Advertiser_1,Campaign_1,2024-10-05,2024-11-16,"Age 24-42, Gaming, India",728x90,183204.20,183204.20
1,2,Advertiser_1,Campaign_2,2024-10-03,2024-11-13,"Age 23-44, Sports, UK",160x600,81431.52,81431.52
2,3,Advertiser_1,Campaign_3,2024-10-18,2024-11-04,"Age 22-34, Finance, Australia",300x250,276829.07,276829.07

In [25]:
dataframes = {}

for file in csv_files:
    file_path = os.path.join(downloads_path, file)

    print(f"\n{'='*50}")
    print(f"АНАЛІЗ ФАЙЛУ: {file}")
    print(f"{'='*50}\n")
    df = pd.read_csv(file_path)
    dataframes[file] = df
    # Збираємо статистику по кожній колонці
    stats = []
    for col in df.columns:
        stats.append({
            'Назва колонки': col,
            'Формат даних': df[col].dtype,
            'К-сть значень (не порожніх)': df[col].count(),
            'К-сть порожніх (NaN)': df[col].isnull().sum(),
            'К-сть унікальних': df[col].nunique()
        })

    # Формуємо та виводимо таблицю зі статистикою
    stats_df = pd.DataFrame(stats)
    print(f"Детальна статистика по колонках для {file}:")
    display(stats_df)

==================================================
АНАЛІЗ ФАЙЛУ: events_header.csv
==================================================

Детальна статистика по колонках для events_header.csv:

,Назва колонки,Формат даних,К-сть значень (не порожніх),К-сть порожніх (NaN),К-сть унікальних
0,EventID,str,10000000,0,10000000
1,AdvertiserName,str,10000000,0,100
2,CampaignName,str,10000000,0,1013
3,CampaignStartDate,str,10000000,0,31
4,CampaignEndDate,str,10000000,0,79
5,CampaignTargetingCriteria,str,10000000,0,255
6,CampaignTargetingInterest,str,10000000,0,8
7,CampaignTargetingCountry,str,10000000,0,5
8,AdSlotSize,str,10000000,0,3
9,UserID,int64,10000000,0,699999
10,Device,str,10000000,0,3
11,Location,str,10000000,0,5
12,Timestamp,str,10000000,0,4502616
13,BidAmount,float64,10000000,0,451
14,AdCost,float64,10000000,0,441
15,WasClicked,bool,10000000,0,2
16,ClickTimestamp,str,499732,9500268,474688
17,AdRevenue,float64,10000000,0,952
18,Budget,float64,10000000,0,1013
19,RemainingBudget,float64,10000000,0,1013

==================================================
АНАЛІЗ ФАЙЛУ: users.csv
==================================================

Детальна статистика по колонках для users.csv:

,Назва колонки,Формат даних,К-сть значень (не порожніх),К-сть порожніх (NaN),К-сть унікальних
0,UserID,int64,700000,0,700000
1,Age,int64,700000,0,48
2,Gender,str,700000,0,2
3,Location,str,700000,0,5
4,Interests,str,700000,0,2080
5,SignupDate,str,700000,0,1501

==================================================
АНАЛІЗ ФАЙЛУ: campaigns.csv
==================================================

Детальна статистика по колонках для campaigns.csv:

,Назва колонки,Формат даних,К-сть значень (не порожніх),К-сть порожніх (NaN),К-сть унікальних
0,CampaignID,int64,1013,0,1013
1,AdvertiserName,str,1013,0,100
2,CampaignName,str,1013,0,1013
3,CampaignStartDate,str,1013,0,31
4,CampaignEndDate,str,1013,0,79
5,TargetingCriteria,str,1013,0,960
6,AdSlotSize,str,1013,0,3
7,Budget,float64,1013,0,1013
8,RemainingBudget,float64,1013,0,1013